cask_args appdir: '/Applications'

tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/fonts"
tap "caskroom/drivers"
tap "caskroom/versions"

brew "ag"
brew "awscli"
brew "bash"
brew "git"
brew "mobile-shell"
brew "carthage"
brew "htop"
brew "httpie"
brew "kubernetes-cli"
brew "libimobiledevice", args: ["HEAD"]
brew "node"
brew "p7zip"
brew "python"
brew "python3"
brew "ruby"
brew "rbenv"
brew "ripgrep"
brew "tmux"
brew "vim"
brew "wget"
brew "jq"
brew "terminal-notifier"
brew "shellcheck"

cask "iterm2"
cask "kindle"
cask "dropbox"
cask "docker"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vagrant"
cask "java8"
cask "google-chrome"
cask "minikube"
cask "macvim"
cask "keepassx"
cask "zoomus"
cask "alfred"
cask "visual-studio"
cask "spectacle"
cask "caskroom/fonts/font-inconsolata"
cask "caskroom/drivers/logitech-options"
