cask_args appdir: '/Applications'

tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/core"

brew "bash"
brew "git"
brew "mobile-shell"
brew "carthage"
brew "docker-cloud"
brew "htop"
brew "kubernetes-cli"
brew "libimobiledevice", args: ["HEAD"]
brew "node"
brew "p7zip"
brew "python"
brew "python3"
brew "ruby"
brew "tmux"
brew "vim"
brew "wget"
brew "jq"

cask "iterm2"
cask "kindle"
cask "dropbox"
cask "virtualbox"
cask "vagrant"
cask "google-chrome"
cask "minikube"
cask "keepassx"
cask "zoomus"
cask "alfred"
cask "caskroom/fonts/font-inconsolata"
